@startmindmap
caption figure 1
header EFWMC Academy
title Nvim Ultimate Editor

+ <&flag>Nvim

** Lsp
*** Clang
*** lua
*** rust
*** java
*** nodejs

left side

** Tips
***:Create plantuml automatically brutly
<code>
plantuml file.puml > file.png
</code>
;
*** Using org-mode
*** Using telescope
*** Using lazygit
*** Using terminal

@endmindmap
